version: "3.8"
services:

# Container management GUI
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
        - 8000:8000
        - 9000:9000
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${DOCKERCONFDIR}/portainer:/data
    restart: unless-stopped

  # Reverse proxy
  swag:
    image: linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${DOMAIN}
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=${EMAIL}
      - DHLEVEL=2048 #optional
      - ONLY_SUBDOMAINS=false #optional
    volumes:
      - ${DOCKERCONFDIR}/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  #yt dl
  youtube-dl:
    image: tzahi12345/youtubedl-material:latest
    container_name: youtube-dl
    ports:
        - 8084:17442
    volumes:
        - ${DOCKERCONFDIR}/youtubedl/appdata:/app/appdata
        - ${DOCKERCONFDIR}/youtubedl/audio:/app/audio
        - ${DOCKERCONFDIR}/youtubedl/subscriptions:/app/subscriptions
        - ${DOCKERCONFDIR}/youtubedl/users:/app/users
        - ${DOCKERCONFDIR}/youtubedl/video:/app/video
    restart: unless-stopped

# Radarr
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    labels:
      - org.hotio.pullio.update=${PULLIO_UPDATE}
      - org.hotio.pullio.notify=${PULLIO_NOTIFY}
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/radarr:/config
      - ${DOCKERSTORAGEDIR}:/data

# Sonarr
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:release
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    labels:
      - org.hotio.pullio.update=${PULLIO_UPDATE}
      - org.hotio.pullio.notify=${PULLIO_NOTIFY}
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/sonarr:/config
      - ${DOCKERSTORAGEDIR}:/data

# Bazarr
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:nightly
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    labels:
      - org.hotio.pullio.update=${PULLIO_UPDATE}
      - org.hotio.pullio.notify=${PULLIO_NOTIFY}
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/bazarr:/config
      - ${DOCKERSTORAGEDIR}:/data/media

  # Torrent client
  transmission:
    # Pinned version due to issue with Ctrl+V
    # https://github.com/transmission/transmission/issues/5298
    image: lscr.io/linuxserver/transmission:4.0.1
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/transmission:/config
      - ${DOCKERSTORAGEDIR}/downloads/torrents:/downloads
    ports:
      - 8003:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  # Torrent indexer proxy
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true #optional
    volumes:
      - ${DOCKERCONFDIR}/jackett:/config
      - ${DOCKERSTORAGEDIR}/downloads/torrents:/downloads
    ports:
      - 8004:9117
    restart: unless-stopped
      
  # SABnzbd
  sabnzbd:
      container_name: sabnzbd
      image: hotio/sabnzbd:latest
      restart: unless-stopped
      logging:
        driver: json-file
        options:
          max-file: ${DOCKERLOGGING_MAXFILE}
          max-size: ${DOCKERLOGGING_MAXSIZE}
      labels:
        - org.hotio.pullio.update=${PULLIO_UPDATE}
        - org.hotio.pullio.notify=${PULLIO_NOTIFY}
        - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
      ports:
        - 8080:8080
        - 9090:9090
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ${DOCKERCONFDIR}/sabnzbd:/config
        - ${DOCKERSTORAGEDIR}/usenet:/data/usenet:rw

# Plex
  plex:
    container_name: plex
    image: ghcr.io/hotio/plex
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    labels:
      - org.hotio.pullio.update=${PULLIO_UPDATE}
      - org.hotio.pullio.notify=${PULLIO_NOTIFY}
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
    ports:
      - 32400:32400
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
      - PLEX_CLAIM_TOKEN=${PLEX_CLAIM_TOKEN}
      - PLEX_ADVERTISE_URL=${PLEX_ADVERTISE_URL}
      - PLEX_NO_AUTH_NETWORKS=
      - PLEX_BETA_INSTALL=${PLEX_BETA_INSTALL}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/plex:/config:rw
      - ${DOCKERSTORAGEDIR}/media:/data/media:rw
#    devices:                                        # optional: if you have a Syno with an Intel CPU with quicksync and want hardware transcoding (only with Plex Pass) uncomment this line.
#      - /dev/dri:/dev/dri                           # optional: if you have a Syno with an Intel CPU with quicksync and want hardware transcoding (only with Plex Pass) uncomment this line.
#    tmpfs:                                          # optional: if you have a Syno with enough RAM, you can uncomment this line to enable transcoding in RAM. uncomment this line.
#      - /transcode                                  # optional: if you have a Syno with enough RAM, you can uncomment this line to enable transcoding in RAM. uncomment this line.