version: "3.8"
services:

  # Dashboard for all these apps
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ${DOCKERCONFDIR}/homarr/configs:/app/data/configs
      - ${DOCKERCONFDIR}/homarr/icons:/app/public/icons
      - ${DOCKERCONFDIR}/homarr/data:/data
    ports:
      - '7575:7575'

  # automatically synchronize recommended settings from the TRaSH guides to your Sonarr/Radarr instances
  # recyclarr:
  #   image: ghcr.io/recyclarr/recyclarr:latest
  #   container_name: recyclarr
  #   user: ${PUID}:${PGID}
  #   volumes:
  #     - ${DOCKERCONFDIR}/recyclarr/config:/config
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}

  # Reverse proxy
  # swag:
  #   image: linuxserver/swag:latest
  #   container_name: swag
  #   cap_add:
  #     - NET_ADMIN
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     - URL=${DOMAIN}
  #     - SUBDOMAINS=wildcard
  #     - VALIDATION=dns
  #     - DNSPLUGIN=cloudflare
  #     - EMAIL=${EMAIL}
  #     - DHLEVEL=2048 #optional
  #     - ONLY_SUBDOMAINS=false #optional
  #   volumes:
  #     - ${DOCKERCONFDIR}/swag:/config
  #   ports:
  #     - 443:443
  #     - 80:80
  #   restart: unless-stopped

  #home assist
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/homeassistant:/config
    ports:
      - 8123:8123 #optional
    #devices:
    #  - /path/to/device:/path/to/device #optional
    restart: unless-stopped

  #overseerr for media discovery
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - ${DOCKERCONFDIR}/overseerr:/app/config
    restart: unless-stopped

  # emulator https://docs.linuxserver.io/images/docker-emulatorjs/
  # emulatorjs:
  #   image: lscr.io/linuxserver/emulatorjs:latest
  #   container_name: emulatorjs
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   volumes:
  #     - ${DOCKERCONFDIR}/emulatorjs:/config
  #     - ${DOCKERSTORAGEDIR}/games:/data
  #   ports:
  #     - 3000:3000
  #     - 80:80
  #     - 4001:4001 #optional
  #   restart: unless-stopped

  #yt dl
  youtube-dl:
    image: tzahi12345/youtubedl-material:latest
    container_name: youtube-dl
    ports:
        - 8084:17442
    volumes:
        - ${DOCKERCONFDIR}/youtubedl/appdata:/app/appdata
        - ${DOCKERCONFDIR}/youtubedl/audio:/app/audio
        - ${DOCKERCONFDIR}/youtubedl/subscriptions:/app/subscriptions
        - ${DOCKERCONFDIR}/youtubedl/users:/app/users
        - ${DOCKERCONFDIR}/youtubedl/video:/app/video
    restart: unless-stopped

# Radarr
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    labels:
      - org.hotio.pullio.update=${PULLIO_UPDATE}
      - org.hotio.pullio.notify=${PULLIO_NOTIFY}
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/radarr:/config
      - ${DOCKERSTORAGEDIR}:/data
    network_mode: service:vpn
    depends_on:
      - vpn

# Sonarr
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:release
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    labels:
      - org.hotio.pullio.update=${PULLIO_UPDATE}
      - org.hotio.pullio.notify=${PULLIO_NOTIFY}
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/sonarr:/config
      - ${DOCKERSTORAGEDIR}:/data
    network_mode: service:vpn
    depends_on:
      - vpn

# Bazarr
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:nightly
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    labels:
      - org.hotio.pullio.update=${PULLIO_UPDATE}
      - org.hotio.pullio.notify=${PULLIO_NOTIFY}
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/bazarr:/config
      - ${DOCKERSTORAGEDIR}/media:/data/media
    network_mode: service:vpn
    depends_on:
      - vpn
      
  # prowlarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/prowlarr:/config
    ports:
      - 9696:9696
    network_mode: service:vpn
    depends_on:
      - vpn
    restart: unless-stopped

  # Nord VPN
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - TOKEN=${NORDVPN_TOKEN}
      - CONNECT=United_Kingdom
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.200/24  # So it can be accessed within the local network
    ports:
      - 8080:8080
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only

  # Torrent client
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8090
    volumes:
      - ${DOCKERCONFDIR}/qbittorrent:/config
      - ${DOCKERSTORAGEDIR}/torrents:/data/torrents:rw
    ports:
      - 8090:8090
      - 6881:6881
      - 6881:6881/udp
    network_mode: service:vpn
    depends_on:
      - vpn
    restart: unless-stopped

  # Torrent client
  # transmission:
  #   image: lscr.io/linuxserver/transmission:latest
  #   container_name: transmission
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     - USER=admin #optional
  #     - PASS=admin #optional
  #   volumes:
  #     - ${DOCKERCONFDIR}/transmission:/config
  #     - ${DOCKERSTORAGEDIR}/torrents:/data/torrents:rw
  #   ports:
  #     - 9091:9091
  #     - 51413:51413
  #     - 51413:51413/udp
  #   restart: unless-stopped
      
  # SABnzbd
  sabnzbd:
      container_name: sabnzbd
      image: hotio/sabnzbd:latest
      restart: unless-stopped
      logging:
        driver: json-file
        options:
          max-file: ${DOCKERLOGGING_MAXFILE}
          max-size: ${DOCKERLOGGING_MAXSIZE}
      labels:
        - org.hotio.pullio.update=${PULLIO_UPDATE}
        - org.hotio.pullio.notify=${PULLIO_NOTIFY}
        - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
      ports:
        - 8080:8080
        - 9090:9090
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ${DOCKERCONFDIR}/sabnzbd:/config
        - ${DOCKERSTORAGEDIR}/usenet:/data/usenet:rw
      network_mode: service:vpn
      depends_on:
        - vpn

# Plex
  plex:
    container_name: plex
    image: ghcr.io/hotio/plex
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    labels:
      - org.hotio.pullio.update=${PULLIO_UPDATE}
      - org.hotio.pullio.notify=${PULLIO_NOTIFY}
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
    ports:
      - 32400:32400
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
      - PLEX_CLAIM_TOKEN=${PLEX_CLAIM_TOKEN}
      - PLEX_ADVERTISE_URL=${PLEX_ADVERTISE_URL}
      - PLEX_NO_AUTH_NETWORKS=
      - PLEX_BETA_INSTALL=${PLEX_BETA_INSTALL}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/plex:/config:rw
      - ${DOCKERSTORAGEDIR}/media:/data/media:rw
    devices:                                        # optional: if you have a Syno with an Intel CPU with quicksync and want hardware transcoding (only with Plex Pass) uncomment this line.
      - /dev/dri:/dev/dri                           # optional: if you have a Syno with an Intel CPU with quicksync and want hardware transcoding (only with Plex Pass) uncomment this line.
    tmpfs:                                          # optional: if you have a Syno with enough RAM, you can uncomment this line to enable transcoding in RAM. uncomment this line.
      - /transcode                                  # optional: if you have a Syno with enough RAM, you can uncomment this line to enable transcoding in RAM. uncomment this line.

  #Transcode media lib from h264 to h265 to drastically reduce storage space
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=MyInternalNode
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${DOCKERCONFDIR}/tdarr/server:/app/server
      - ${DOCKERCONFDIR}/tdarr/configs:/app/configs
      - ${DOCKERCONFDIR}/tdarr/logs:/app/logs
      - ${DOCKERSTORAGEDIR}/media:/media
      - ${DOCKERCONFDIR}/tdarr/transcode_cache:/temp

    devices:
      - /dev/dri:/dev/dri
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         count: all
    #         capabilities: [gpu]

  # node example
  # tdarr-node:
  #   container_name: tdarr-node
  #   image: ghcr.io/haveagitgat/tdarr_node:latest
  #   restart: unless-stopped
  #   network_mode: service:tdarr
  #   environment:
  #     - TZ=${TZ}
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - UMASK_SET=002
  #     - nodeName=MyExternalNode
  #     - serverIP=0.0.0.0
  #     - serverPort=8266
  #     - inContainer=true
  #     - ffmpegVersion=6
  #     - NVIDIA_DRIVER_CAPABILITIES=all
  #     - NVIDIA_VISIBLE_DEVICES=all

  #   volumes:
  #     - ${DOCKERCONFDIR}/tdarr/configs:/app/configs
  #     - ${DOCKERCONFDIR}/tdarr/logs:/app/logs
  #     - ${DOCKERSTORAGEDIR}/media:/media
  #     - ${DOCKERCONFDIR}/tdarr/transcode_cache:/temp

  #   devices:
  #     - /dev/dri:/dev/dri
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - driver: nvidia
  #           count: all
  #           capabilities: [gpu]